# Generated by Django 3.0.6 on 2020-06-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_userpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Paper')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='userpaper',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='userpaper',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UserPaper',
        ),
        migrations.AddField(
            model_name='profile',
            name='papers',
            field=models.ManyToManyField(through='papers.UserSavedPaper', to='papers.Paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='users',
            field=models.ManyToManyField(through='papers.UserSavedPaper', to='papers.Profile'),
        ),
    ]
