# Generated by Django 3.0.6 on 2020-06-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_papers'),
        ('papers', '0008_auto_20200615_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='_paper_rating_+', through='papers.Rating', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='papers.Paper'),
        ),
    ]
