# Generated by Django 3.0.6 on 2020-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_papers'),
        ('papers', '0009_auto_20200615_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='rating',
        ),
        migrations.AddField(
            model_name='paper',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_paper_comments_+', through='papers.Comment', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='paper',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='_paper_ratings_+', through='papers.Rating', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_papers', through='papers.UserSavedPaper', to='accounts.Profile'),
        ),
    ]
