# Generated by Django 3.0.6 on 2020-06-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_auto_20200615_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='profile',
        ),
    ]
