# Generated by Django 3.0.6 on 2020-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_papers'),
        ('papers', '0011_auto_20200615_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_made', through='papers.Comment', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings_given', through='papers.Rating', to='accounts.Profile'),
        ),
    ]
