# Generated by Django 3.0.6 on 2020-06-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_papers'),
        ('papers', '0012_auto_20200615_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='comments',
            new_name='commented_by_users',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='ratings',
            new_name='rated_by_users',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='paper',
            name='saved_by_users',
            field=models.ManyToManyField(blank=True, related_name='papers_saved', through='papers.UserSavedPaper', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='papers.Paper'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.Profile'),
        ),
    ]
