# Generated by Django 3.0.6 on 2020-06-29 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200629_1551'),
        ('papers', '0013_auto_20200615_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='rating',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='papers.Paper'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='usersavedpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to='papers.Paper'),
        ),
        migrations.AlterField(
            model_name='usersavedpaper',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to='accounts.Profile'),
        ),
    ]
