# Generated by Django 3.0.6 on 2020-07-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_auto_20200708_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='commented_by_users',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='rated_by_users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
