# Generated by Django 3.0.6 on 2020-07-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile'),
        ('papers', '0017_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='commented_by_users',
            field=models.ManyToManyField(blank=True, related_name='comments_made', through='papers.Comment', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='paper',
            name='rated_by_users',
            field=models.ManyToManyField(blank=True, related_name='ratings_given', through='papers.Rating', to='accounts.Profile'),
        ),
    ]
