# Generated by Django 3.0.6 on 2020-07-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile'),
        ('papers', '0018_auto_20200708_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to='papers.Paper')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='saved_by_users',
            field=models.ManyToManyField(blank=True, related_name='papers_saved', through='papers.UserSavedPaper', to='accounts.Profile'),
        ),
    ]
