# Generated by Django 3.0.6 on 2020-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_auto_20200602_1406'),
        ('accounts', '0002_remove_profile_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='papers',
            field=models.ManyToManyField(blank=True, through='papers.UserSavedPaper', to='papers.Paper'),
        ),
    ]
