# Generated by Django 3.0.6 on 2020-06-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='papers',
        ),
    ]
